/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#00355f",
        "primary-container": "#0f4c81",
        "on-primary": "#ffffff",
        "on-primary-container": "#8ebdf9",
        "primary-fixed": "#d2e4ff",
        "primary-fixed-dim": "#a0c9ff",
        "on-primary-fixed": "#001c37",
        "on-primary-fixed-variant": "#07497d",
        "secondary": "#515f74",
        "secondary-container": "#d5e3fd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#57657b",
        "secondary-fixed": "#d5e3fd",
        "secondary-fixed-dim": "#b9c7e0",
        "tertiary": "#003756",
        "tertiary-container": "#004e78",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#74c1ff",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#42474f",
        "outline": "#727780",
        "outline-variant": "#c2c7d1",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-code-sm": ["JetBrains Mono", "monospace"],
        "label-code-md": ["JetBrains Mono", "monospace"],
        "label-code-lg": ["JetBrains Mono", "monospace"],
        "tabular-vitals": ["Inter", "monospace", "sans-serif"],
      },
      spacing: {
        "gutter": "1rem",
        "gutter-dense": "0.5rem",
        "margin": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
      }
    },
  },
  plugins: [],
}
